"""
EduRAG AI — RAG-Based Video Lecture Teaching Assistant
======================================================

Layman Explanation:
-------------------
This file runs the web server for EduRAG AI, a Smart AI Teaching Assistant for video courses.

What this application does:
1. Loads pre-computed 1024-dimensional vector embeddings of video transcripts (generated by OpenAI Whisper & Ollama bge-m3).
2. Listens for student questions typed into the Web UI.
3. Converts the student's question into a 1024-dimensional math vector and calculates Cosine Similarity to find the most relevant video lecture seconds.
4. Synthesizes a helpful answer citing exact video timestamps and streams MP3 audio with seeking support so students can jump straight to the answer!
"""

import http.server
import socketserver
import json
import urllib.parse
import os
import requests
import joblib
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

PORT = int(os.environ.get("PORT", 5000))
EMBEDDINGS_FILE = "embeddings.joblib"

# Global variable to store vector embeddings dataset in memory
df_embeddings = None


def load_embeddings():
    """Loads vector embeddings database into memory on server startup."""
    global df_embeddings
    if os.path.exists(EMBEDDINGS_FILE):
        print(f"Loading '{EMBEDDINGS_FILE}' into memory...")
        df_embeddings = joblib.load(EMBEDDINGS_FILE)
        print(f"Loaded {len(df_embeddings)} vector chunks successfully!")
    elif os.path.exists("embeddings.json"):
        print("Loading 'embeddings.json' into memory...")
        import pandas as pd
        with open("embeddings.json", encoding="utf-8") as f:
            data = json.load(f)
        df_embeddings = pd.DataFrame.from_records(data)
        print(f"Loaded {len(df_embeddings)} vector chunks successfully!")
    else:
        print("Warning: No embeddings file found!")


def get_query_embedding(query_text, model_name="bge-m3"):
    """Generates a 1024-dimensional semantic embedding vector with TF-IDF cloud fallback."""
    url = "http://localhost:11434/api/embed"
    payload = {"model": model_name, "input": [query_text]}
    try:
        response = requests.post(url, json=payload, timeout=3)
        if response.status_code == 200:
            return response.json()["embeddings"][0]
    except Exception:
        pass
    return None


def resolve_audio_filename(file_name):
    """Maps JSON transcript filename to exact existing MP3 audio filename in audios/ folder."""
    if not file_name:
        return ""
    
    base_mp3 = file_name.replace('.json', '.mp3')
    if os.path.exists(os.path.join("audios", base_mp3)):
        return base_mp3
        
    if "_" in file_name:
        num_prefix = file_name.split("_")[0].lstrip("0")
        for audio_f in os.listdir("audios"):
            if audio_f.split("_")[0].lstrip("0") == num_prefix:
                return audio_f
                
    return base_mp3


def search_similar_chunks(query_vector, query_text="", top_k=4):
    """Computes Cosine Similarity math between user question vector and video lecture chunks."""
    if df_embeddings is None or len(df_embeddings) == 0:
        return []
    
    if query_vector is not None:
        chunk_embeddings = np.array(df_embeddings['embedding'].tolist())
        query_vector_2d = np.array([query_vector])
        similarities = cosine_similarity(query_vector_2d, chunk_embeddings)[0]
    else:
        # High-precision TF-IDF fallback for cloud deployments
        from sklearn.feature_extraction.text import TfidfVectorizer
        texts = df_embeddings['text'].astype(str).tolist()
        vectorizer = TfidfVectorizer(stop_words='english')
        tfidf_matrix = vectorizer.fit_transform(texts + [query_text])
        similarities = cosine_similarity(tfidf_matrix[-1:], tfidf_matrix[:-1])[0]
    
    df_copy = df_embeddings.copy()
    df_copy['similarity'] = similarities
    top_df = df_copy.sort_values(by='similarity', ascending=False).head(top_k)
    
    results = []
    for _, row in top_df.iterrows():
        file_name = row.get('file_name', '')
        title = row.get('title', '')
        if not title:
            title = file_name.replace('.json', '').replace('.mp3', '')
        
        if " - Tutorial #" in title:
            clean_title = title.split(" - Tutorial #")[0]
        elif "_" in title:
            clean_title = title.split("_", 1)[1]
        else:
            clean_title = title

        audio_file = resolve_audio_filename(file_name)

        results.append({
            "chunk_id": int(row.get('chunk_id', 0)),
            "file_name": file_name,
            "title": clean_title,
            "start": float(row.get('start', 0.0)),
            "end": float(row.get('end', 0.0)),
            "text": str(row.get('text', '')).strip(),
            "similarity": float(row['similarity']),
            "audio_file": audio_file
        })
    return results


def generate_llm_response(prompt, model_name="llama3"):
    """Queries Ollama LLM to generate candidate response from retrieved context."""
    url = "http://localhost:11434/api/generate"
    payload = {"model": model_name, "prompt": prompt, "stream": False}
    try:
        res = requests.post(url, json=payload, timeout=30)
        if res.status_code == 200:
            return res.json().get("response", "").strip()
    except Exception:
        pass
    return None


class ReusableTCPServer(socketserver.TCPServer):
    """Allows rapid server restarts without address-already-in-use port errors."""
    allow_reuse_address = True


class RAGServerHandler(http.server.SimpleHTTPRequestHandler):
    """HTTP Request Handler routing GET and POST API endpoints."""
    
    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        
        # Serve main Web UI page
        if parsed.path in ["/", "/index.html"]:
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            with open("index.html", "rb") as f:
                self.wfile.write(f.read())
            return
            
        # Serve audio files from audios/ with HTTP Range (206 Partial Content) support for seeking & timestamps
        if parsed.path.startswith("/audios/"):
            audio_rel_path = urllib.parse.unquote(parsed.path[1:])
            
            if not os.path.exists(audio_rel_path):
                audio_filename = os.path.basename(audio_rel_path)
                resolved_name = resolve_audio_filename(audio_filename)
                audio_rel_path = os.path.join("audios", resolved_name)

            if os.path.exists(audio_rel_path):
                file_size = os.path.getsize(audio_rel_path)
                range_header = self.headers.get('Range')

                if range_header:
                    try:
                        byte_range = range_header.strip().split("=")[1]
                        if "-" in byte_range:
                            start_str, end_str = byte_range.split("-", 1)
                            start_byte = int(start_str) if start_str else 0
                            end_byte = int(end_str) if end_str else file_size - 1
                        else:
                            start_byte = int(byte_range)
                            end_byte = file_size - 1
                    except Exception:
                        start_byte = 0
                        end_byte = file_size - 1

                    if start_byte >= file_size:
                        start_byte = file_size - 1
                    if end_byte >= file_size:
                        end_byte = file_size - 1

                    content_length = end_byte - start_byte + 1

                    self.send_response(206)
                    self.send_header("Content-Type", "audio/mpeg")
                    self.send_header("Accept-Ranges", "bytes")
                    self.send_header("Content-Range", f"bytes {start_byte}-{end_byte}/{file_size}")
                    self.send_header("Content-Length", str(content_length))
                    self.end_headers()

                    with open(audio_rel_path, "rb") as f:
                        f.seek(start_byte)
                        self.wfile.write(f.read(content_length))
                    return
                else:
                    self.send_response(200)
                    self.send_header("Content-Type", "audio/mpeg")
                    self.send_header("Accept-Ranges", "bytes")
                    self.send_header("Content-Length", str(file_size))
                    self.end_headers()
                    with open(audio_rel_path, "rb") as f:
                        self.wfile.write(f.read())
                    return
            else:
                self.send_error(404, "Audio file not found")
                return

        # Serve course metadata API
        if parsed.path == "/api/course_info":
            info = {
                "total_chunks": len(df_embeddings) if df_embeddings is not None else 0,
                "embedding_model": "Ollama bge-m3 (1024-dim)",
                "topics": [
                    "Installing VS Code & How Websites Work",
                    "Your First HTML Website",
                    "Basic Structure of an HTML Website",
                    "Heading, Paragraphs and Links",
                    "Image, Lists, and Tables in HTML",
                    "SEO and Core Web Vitals in HTML",
                    "Forms and Input Tags in HTML",
                    "Inline & Block Elements in HTML",
                    "Id & Classes in HTML",
                    "Video, Audio & Media in HTML",
                    "Semantic Tags in HTML"
                ]
            }
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(info).encode('utf-8'))
            return
            
        return super().do_GET()

    def do_POST(self):
        """Processes incoming RAG vector search requests."""
        if self.path == "/api/search":
            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length)
            
            try:
                data = json.loads(post_data.decode('utf-8'))
                query = data.get("query", "").strip()
                
                if not query:
                    self.send_error(400, "Empty query")
                    return
                
                print(f"Incoming Search Query: '{query}'")
                query_vector = get_query_embedding(query)
                matches = search_similar_chunks(query_vector, query_text=query, top_k=4)
                
                # Construct RAG Prompt
                context_lines = []
                for m in matches:
                    context_lines.append(f"- Video '{m['title']}' ({m['start']:.1f}s-{m['end']:.1f}s): {m['text']}")
                
                context_str = "\n".join(context_lines)
                prompt = f"""You are an AI Teaching Assistant for a Web Development video course.
Answer the user's question clearly using ONLY the provided course context below.
Cite the relevant video title and timestamps.

CONTEXT:
{context_str}

USER QUESTION:
{query}

ANSWER:"""

                ai_response = generate_llm_response(prompt)
                if not ai_response:
                    ai_response = f"Based on your search query **\"{query}\"**, the most relevant tutorial videos are listed below. Key context: {matches[0]['text']}"

                response_data = {
                    "query": query,
                    "matches": matches,
                    "answer": ai_response
                }
                
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps(response_data).encode('utf-8'))
            except Exception as e:
                print(f"Error processing search: {e}")
                self.send_response(500)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"error": str(e)}).encode('utf-8'))
            return

        self.send_error(404, "Endpoint not found")


if __name__ == "__main__":
    load_embeddings()
    server_address = ('', PORT)
    httpd = ReusableTCPServer(server_address, RAGServerHandler)
    print(f"\n==========================================================")
    print(f"RAG AI Teaching Assistant Web Server Running!")
    print(f"Access Web UI at: http://localhost:{PORT}")
    print(f"==========================================================\n")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down web server...")
        httpd.server_close()
